safe: false
markdown: redcarpet
highlighter: pygments
baseurl: /
url: http://docs.divshot.io
exclude:
  - _assets
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - README.md
  - Guardfile
  - divshot.json
  - _vendor
  - vendor

assets:
  sources:
    - _assets/images
    - _assets/images/architect
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/stylesheets
    - _vendor/javascripts
    - _vendor/webfonts